/**
 * Google Places API supported place types (Table A - primary types for filtering)
 * @see https://developers.google.com/maps/documentation/places/web-service/place-types
 */
export const PLACE_TYPES = [
  { value: "restaurant", label: "Restaurant" },
  { value: "cafe", label: "Café" },
  { value: "bar", label: "Bar" },
  { value: "bakery", label: "Bakery" },
  { value: "meal_delivery", label: "Meal Delivery" },
  { value: "meal_takeaway", label: "Meal Takeaway" },
  { value: "food", label: "Food" },
  { value: "lodging", label: "Hotel / Lodging" },
  { value: "shopping_mall", label: "Shopping Mall" },
  { value: "supermarket", label: "Supermarket" },
  { value: "convenience_store", label: "Convenience Store" },
  { value: "clothing_store", label: "Clothing Store" },
  { value: "electronics_store", label: "Electronics Store" },
  { value: "furniture_store", label: "Furniture Store" },
  { value: "home_goods_store", label: "Home Goods Store" },
  { value: "jewelry_store", label: "Jewelry Store" },
  { value: "shoe_store", label: "Shoe Store" },
  { value: "book_store", label: "Book Store" },
  { value: "pet_store", label: "Pet Store" },
  { value: "store", label: "Store" },
  { value: "beauty_salon", label: "Beauty Salon" },
  { value: "hair_care", label: "Hair Care" },
  { value: "spa", label: "Spa" },
  { value: "gym", label: "Gym" },
  { value: "physiotherapist", label: "Physiotherapist" },
  { value: "dentist", label: "Dentist" },
  { value: "doctor", label: "Doctor" },
  { value: "hospital", label: "Hospital" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "veterinary_care", label: "Veterinary Care" },
  { value: "lawyer", label: "Lawyer" },
  { value: "accounting", label: "Accounting" },
  { value: "insurance_agency", label: "Insurance Agency" },
  { value: "real_estate_agency", label: "Real Estate Agency" },
  { value: "travel_agency", label: "Travel Agency" },
  { value: "car_rental", label: "Car Rental" },
  { value: "car_dealer", label: "Car Dealer" },
  { value: "car_repair", label: "Car Repair" },
  { value: "gas_station", label: "Gas Station" },
  { value: "parking", label: "Parking" },
  { value: "electrician", label: "Electrician" },
  { value: "plumber", label: "Plumber" },
  { value: "locksmith", label: "Locksmith" },
  { value: "moving_company", label: "Moving Company" },
  { value: "roofing_contractor", label: "Roofing Contractor" },
  { value: "general_contractor", label: "General Contractor" },
  { value: "painter", label: "Painter" },
  { value: "school", label: "School" },
  { value: "university", label: "University" },
  { value: "library", label: "Library" },
  { value: "museum", label: "Museum" },
  { value: "art_gallery", label: "Art Gallery" },
  { value: "movie_theater", label: "Movie Theater" },
  { value: "night_club", label: "Night Club" },
  { value: "bowling_alley", label: "Bowling Alley" },
  { value: "stadium", label: "Stadium" },
  { value: "amusement_park", label: "Amusement Park" },
  { value: "aquarium", label: "Aquarium" },
  { value: "zoo", label: "Zoo" },
  { value: "tourist_attraction", label: "Tourist Attraction" },
  { value: "church", label: "Church" },
  { value: "mosque", label: "Mosque" },
  { value: "synagogue", label: "Synagogue" },
  { value: "hindu_temple", label: "Hindu Temple" },
  { value: "place_of_worship", label: "Place of Worship" },
  { value: "embassy", label: "Embassy" },
  { value: "fire_station", label: "Fire Station" },
  { value: "police", label: "Police" },
  { value: "post_office", label: "Post Office" },
  { value: "local_government_office", label: "Local Government Office" },
  { value: "bank", label: "Bank" },
  { value: "atm", label: "ATM" },
  { value: "finance", label: "Finance" },
  { value: "laundry", label: "Laundry" },
  { value: "storage", label: "Storage" },
  { value: "florist", label: "Florist" },
  { value: "funeral_home", label: "Funeral Home" },
  { value: "cemetery", label: "Cemetery" },
  { value: "liquor_store", label: "Liquor Store" },
  { value: "hardware_store", label: "Hardware Store" },
] as const;

export type PlaceTypeValue = (typeof PLACE_TYPES)[number]["value"];
